-- =====================================================
-- HISAB SYSTEM - FIXED DATABASE SCHEMA
-- =====================================================

-- 1. Create Accounts table
CREATE TABLE accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Entries table with constraints
CREATE TABLE entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT REFERENCES accounts(id) ON DELETE CASCADE NOT NULL,
  amount DECIMAL(15,2) NOT NULL CHECK (amount > 0),
  type TEXT NOT NULL CHECK (type IN ('deposit', 'withdrawal')),
  description TEXT,
  utr_number TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Coins table (Single row for global balance)
CREATE TABLE coins (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  balance DECIMAL(15,2) DEFAULT 100000,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Indexes for better performance
CREATE INDEX idx_entries_account_id ON entries(account_id);
CREATE INDEX idx_entries_created_at ON entries(created_at);
CREATE INDEX idx_entries_type ON entries(type);

-- 5. Create View for account totals
CREATE OR REPLACE VIEW account_totals AS
SELECT
  a.id as account_id,
  a.name as account_name,
  COALESCE(SUM(CASE WHEN e.type = 'deposit' THEN e.amount ELSE 0 END), 0) as total_deposit,
  COALESCE(SUM(CASE WHEN e.type = 'withdrawal' THEN e.amount ELSE 0 END), 0) as total_withdrawal,
  COALESCE(SUM(CASE WHEN e.type = 'deposit' THEN e.amount ELSE -e.amount END), 0) as balance
FROM accounts a
LEFT JOIN entries e ON a.id = e.account_id
GROUP BY a.id, a.name;

-- 6. Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE entries;
ALTER PUBLICATION supabase_realtime ADD TABLE coins;

-- =====================================================
-- TO ADD UTR COLUMN TO EXISTING TABLE, RUN:
-- ALTER TABLE entries ADD COLUMN utr_number TEXT;
-- =====================================================
